---
- hosts: all
  become: true

  roles:
    - role: ansible_role_pik8s

  tasks:
    - name: create local .kube/config
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        flat: true
      when: pik8s_cluster_role == 'master'

- import_playbook: playbooks/metallb.yml

#- import_playbook: playbooks/dashboard.yml
#  when: pik8s_cluster_role == 'master'
#
