apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: nickdoes.io
      protocol: layer2
      addresses:
      - {{ metallb_pool_start }}-{{ metallb_pool_end }}
      avoid-buggy-ips: true
      auto-assign: true
